---
name: build
on: [push]
jobs:
  test:
    runs-on: ubuntu-18.04
    env:
      ROLE_NAME: canonical_livepatch
    strategy:
      matrix:
        distro: [ubuntu1604, ubuntu1804, ubuntu2004]
    steps:
      - name: Checkout with the directory name of actual Ansible Galaxy role name.
        uses: actions/checkout@v2
        with:
          path: "tsukune_ch.${{ env.ROLE_NAME }}"
      - name: ls
      - name: pwd
